sudo: required
services:
  - docker

before_install:
- docker build -t wtuttle/react-test -f ./client/Dockerfile.dev ./client

script:
  - - docker run -e CI=true wtuttle/react-test npm test

after_success:
  - docker build -t wtuttle/multi:client ./client
  - docker build -t wtuttle/multi:server ./server
  - docker build -t wtuttle/multi:nginx ./nginx
  - docker build -t wtuttle/multi:worker ./worker

#log into docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

#push to docker
  - docker push wtuttle/multi:client
  - docker push wtuttle/multi:server
  - docker push wtuttle/multi:nginx
  - docker push wtuttle/multi:worker