sudo: required
services:
  - docker

before_install:
- docker build -t will/react-test -f ./client/Dockerfile.dev ././client/Dockerfile.dev

script:
  - docker run will/react-test npn test -- --cover

after_success:
  - docker build -t will/multi-client ./client
  - docker build -t will/multi-server ./server
  - docker build -t will/multi-nginx ./nginx
  - docker build -t will/multi-worker ./worker